# Generated by Django 3.2.6 on 2021-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210805_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['date_added']},
        ),
    ]
