# Generated by Django 3.2.6 on 2021-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='post',
        ),
    ]
