# Generated by Django 3.2.6 on 2021-08-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_author_comments_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'Comments'},
        ),
    ]
