# Generated by Django 3.2.6 on 2021-08-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210813_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_reply',
        ),
    ]
